#!/usr/bin/perl

# Dump heap library in 'C' code

use strict;
use warnings;

die "Usage : $0 <architecture>\n" unless($ARGV[0]);

my $LIBHEAP  = "./libheap-$ARGV[0].so";
my $FILE_OUT = "src/heap/libheap.c";
my $VAR_NAME = "global_libheap";
my $HEADER   = "include/global_libheap.h";

my $len = dump_file($LIBHEAP, $FILE_OUT, $VAR_NAME);
print " GEN $FILE_OUT\n";

write_header($HEADER, $len, $VAR_NAME);
print " GEN $HEADER\n";

sub dump_file {
    my ($in, $out, $name) = @_;

    die $@ if(!open IN, $in);
    die $@ if(!open OUT, '>', $out);

    print OUT "/* Generated by script $0, do not edit */\n\n";
    print OUT "#ifndef __WINDOWS__\n";
    print OUT "unsigned char " . $name . "[] = {";

    my $len = 0;
    my $buf;

    while(read IN, $buf, 1) {

        if($len % 16 == 0) {
            print OUT "\n    ";
        }

        printf OUT "0x%.2x", ord($buf);
        print OUT ", " if(!eof(IN));

        $len++;
    }

    print OUT "\n};\n\n";
    print OUT "#endif\n";
    close OUT;
    close IN;

    return $len;
}

sub write_header {
    my ($out, $len, @names) = @_;

    open OUT, '>', $out || die $@;

    print OUT "/* File generated by script $0, do not edit */\n\n";
    print OUT "#ifndef DEF_LIBHEAP_H\n";
    print OUT "#define DEF_LIBHEAP_H\n\n";

    foreach my $n(@names) {
        print OUT "extern unsigned char " . $n . "[$len];\n";
    }

    print OUT "\n#endif\n\n";

    close OUT;
}
